services:
  1baspnet:
     image: italcom.azurecr.io/onebgold:${1BGOLD_TAG}
     environment:
      - ASPNETCORE_URLS=https://+:444;http://+:81
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASP_CERT_PWD}
      - ASPNETCORE_HTTPS_PORT=444
      - ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=${POSTGRES_DBNAME};Integrated Security=false;Pooling=true;
      - AllowedHosts=*
      - AppSettings__Secret=${ASP_SECRET}
      - AppSettings__Issuer=https://localhost:5000
      - Kestrel__EndPoints__Https__Url=https://0.0.0.0:444
      - 1BGOLD_TAG: ${1BGOLD_TAG}
      - 1BGOLD_HTTP_PORT: ${1BGOLD_HTTP_PORT}
      - 1BGOLD_CUSTOMER_CODE: ${1BGOLD_CUSTOMER_CODE}
     volumes:
       - wwwroot:/app/wwwroot
       - attachments:/app/Attachments
       - ${DIR}/certs:/https:ro
     restart: always
     ports:
      #- '444:444'
      - ${1BGOLD_HTTP_PORT}:80
     networks:
      1b_db_net:

volumes:

  attachments:
    driver: local
    name: ${1BGOLD_CUSTOMER_CODE}-attachments
  wwwroot:
    driver: local
    name: ${1BGOLD_CUSTOMER_CODE}-wwwroot
networks:
  1b_db_net:
    external: true