services:
  webapplicationcontainertest:
    image: italcom.azurecr.io/webapplicationcontainertest:latest
    environment:
      TEST_PARAM_1: ${TEST_PARAM_1}
      TEST_PARAM_2: test_2
    ports:
      - 92:8080
    restart: always

