services:
  webapplicationcontainertest:
    image: italcom.azurecr.io/webapplicationcontainertest:${VERSION}
    environment:
      #TEST_PARAM_1: ${TEST_PARAM_1}
      TEST_PARAM_2: test_2
      TEST_PARAM_3: test_3
      HTTP_PORT: ${HTTP_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_VERSION: ${VERSION}
      APP_CUSTOMER_CODE: ${APP_CUSTOMER_CODE}
    restart: always
    env_file:
      - path: ./.env
        required: true # default
      - path: ./stack.env
        required: true # default
    #  - path: ./override.env
    #    required: false
    ports:
      - ${HTTP_PORT}:8080
    #  - ${HTTP_PORT:-95}:8080
    volumes:
      - app-attachments:/app/attachments
  ### Volumes Setup ###
volumes:
  app-attachments:
    name: ${APP_CUSTOMER_CODE}-app-attachments
    #  external:
    #    name: ${APP_CUSTOMER_CODE}_app_attachments