services:
  webapplicationcontainertest:
    image: italcom.azurecr.io/webapplicationcontainertest:latest
    environment:
      #TEST_PARAM_1: ${TEST_PARAM_1}
      TEST_PARAM_2: test_2
      TEST_PARAM_3: test_3

    restart: always
    # env_file:
    #   - path: ./.env
    #    required: true # default
    #  - path: ./stack.env
    #    required: true # default
    #  - path: ./override.env
    #    required: false
    ports:
      - 1110:8080
      - $HTTP_PORT:8080
